version: "3"

services:
  app:
    build: .
    ports:
      - "2222:22"
    cap_add:
      - "sys_ptrace"
    security_opt: # options needed for gdb debugging
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - .:/app
